'use client';

import { useMemo, useState } from 'react';
import { Download, FileBarChart2, Printer, Sparkles, TrendingDown, TrendingUp } from 'lucide-react';
import { useDataContext } from '@/context/data-context';
import { Button } from '@/components/ui/button';
import { DeanPage } from '../dean-ui';
import { exportToCsv } from '@/lib/utils';
import { generateClassSummary } from '@/ai/flows/generate-class-summary';
import { useToast } from '@/hooks/use-toast';

export default function Reports(){
  const {students,attendance}=useDataContext();
  const [range,setRange]=useState('This Month'); const [entity,setEntity]=useState('Entire Department'); const [from,setFrom]=useState(''); const [to,setTo]=useState(''); const [summary,setSummary]=useState(''); const {toast}=useToast();
  const rows=useMemo(()=>students.map((s,i)=>{const a=attendance.filter(x=>x.studentId===s.id);const p=a.filter(x=>x.status==='present').length,ab=a.filter(x=>x.status==='absent').length,l=a.filter(x=>x.status==='late').length;return{student:s.name,studentId:s.id,rollNo:String(s.email||'').match(/^(\d+)@/)?.[1] || s.id,class:'II-A',attendance:a.length?Math.round((p+l)/a.length*100):null,present:p,absent:ab,late:l,risk:a.length ? (((p+l)/a.length*100)<75?'Attention':'On Track') : 'No data'}}),[students,attendance]);
  const generate=async()=>{try{const r=await generateClassSummary({className:'II-A',date:new Date().toISOString().split('T')[0],attendanceData:JSON.stringify(attendance.slice(0,50).map(a=>({studentName:students.find(s=>s.id===a.studentId)?.name||'Student',status:a.status})))});setSummary(r.summary)}catch{toast({variant:'destructive',title:'AI analysis unavailable',description:'Please try again.'})}};
  return <DeanPage title="Attendance Reports" subtitle="Generate department, class, section, student, teacher, subject and date-range reports.">
    <div className="grid gap-3 rounded-2xl border bg-white p-4 shadow-sm md:grid-cols-2 xl:grid-cols-5"><select value={range} onChange={e=>setRange(e.target.value)} className="h-10 rounded-md border px-3 text-sm"><option>Today</option><option>This Week</option><option>This Month</option><option>Semester</option><option>Custom Date Range</option></select><select value={entity} onChange={e=>setEntity(e.target.value)} className="h-10 rounded-md border px-3 text-sm"><option>Entire Department</option><option>Class</option><option>Section</option><option>Student</option><option>Teacher</option><option>Subject</option></select>{range==='Custom Date Range'?<><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="h-10 rounded-md border px-3 text-sm"/><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="h-10 rounded-md border px-3 text-sm"/></>:<div className="flex items-center rounded-xl bg-[#f5f3fc] px-3 text-xs font-semibold text-[#37336e]">{range} · {entity}</div>}<div className="flex gap-2"><Button onClick={()=>exportToCsv('attendavision-dean-report.csv',rows)}><Download className="mr-2 h-4 w-4"/>CSV</Button><Button variant="outline" onClick={()=>window.print()}><Printer className="mr-2 h-4 w-4"/>Print</Button></div></div>
    <div className="grid gap-4 sm:grid-cols-3"><Summary title="Average attendance" value={`${rows.filter(r=>r.attendance!==null).length?Math.round(rows.filter(r=>r.attendance!==null).reduce((n,r)=>n+(r.attendance||0),0)/rows.filter(r=>r.attendance!==null).length):0}%`} icon={TrendingUp}/><Summary title="Students below requirement" value={rows.filter(r=>r.attendance!==null && r.attendance<75).length} icon={TrendingDown}/><Summary title="Records included" value={rows.reduce((n,r)=>n+r.present+r.absent+r.late,0)} icon={FileBarChart2}/></div>
    <div className="overflow-x-auto rounded-2xl border bg-white shadow-sm"><table className="w-full min-w-[800px] text-sm"><thead><tr className="bg-[#fafafe] text-left text-xs text-slate-500"><th className="p-4">Student</th><th className="p-4">Class</th><th className="p-4">Attendance %</th><th className="p-4">Present</th><th className="p-4">Absent</th><th className="p-4">Late</th><th className="p-4">Status</th></tr></thead><tbody>{rows.map(r=><tr className="border-t" key={r.studentId}><td className="p-4 font-semibold">{r.student}<span className="block text-xs text-slate-400">ID {r.studentId} · Roll {r.rollNo}</span></td><td className="p-4">{r.class}</td><td className="p-4 font-black">{r.attendance === null ? '—' : `${r.attendance}%`}</td><td className="p-4 text-emerald-600">{r.present}</td><td className="p-4 text-rose-600">{r.absent}</td><td className="p-4 text-amber-600">{r.late}</td><td className="p-4">{r.risk}</td></tr>)}</tbody></table></div>
    <div className="rounded-2xl border border-violet-100 bg-[#f5f2ff] p-5"><div className="flex items-center gap-2 font-black"><Sparkles className="h-5 w-5 text-[#5b51a3]"/>AI Attendance Analysis</div><p className="mt-1 text-xs text-slate-500">Assistant-generated analysis only. The Dean remains the final academic decision-maker.</p><Button className="mt-3" onClick={generate}>Generate class summary</Button>{summary&&<p className="mt-4 rounded-xl bg-white p-4 text-sm leading-6">{summary}</p>}</div>
  </DeanPage>
}
function Summary({title,value,icon:Icon}:{title:string;value:string|number;icon:any}){return <div className="rounded-2xl border bg-white p-5 shadow-sm"><Icon className="h-5 w-5 text-[#5b51a3]"/><p className="mt-2 text-2xl font-black">{value}</p><p className="text-sm text-slate-500">{title}</p></div>}
