'use client';

import { useMemo, useState } from 'react';
import { CalendarDays, ChevronRight, Search, Users, AlertTriangle } from 'lucide-react';
import { useDataContext } from '@/context/data-context';
import { DeanPage } from '../dean-ui';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { SUBJECTS } from '@/lib/timetable';

const required=75;
export default function Classes(){
  const {students,attendance}=useDataContext();
  const [open,setOpen]=useState(false); const [date,setDate]=useState(new Date().toISOString().split('T')[0]); const [subject,setSubject]=useState('all'); const [q,setQ]=useState('');
  const allRecords=attendance.filter(a=>!subject||subject==='all'||a.classId===subject);
  const pct=allRecords.length?Math.round(allRecords.filter(a=>a.status!=='absent').length/allRecords.length*100):null;
  const rows=students.filter(s=>s.name.toLowerCase().includes(q.toLowerCase())).map((s,i)=>{const a=attendance.filter(x=>x.studentId===s.id&&(subject==='all'||x.classId===subject));const p=a.filter(x=>x.status==='present').length,ab=a.filter(x=>x.status==='absent').length,l=a.filter(x=>x.status==='late').length,pc=a.length?Math.round((p+l)/a.length*100):null;return{s,i,p,ab,l,pc,risk:pc===null?'No data':pc<65?'High':pc<required?'Medium':'Low',day:a.filter(x=>x.date===date)}});
  return <DeanPage title="Classes" subtitle="View class/section performance, student risk and date-based attendance.">
    <div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#f0eefb] text-[#37336e]"><Users/></div><div><p className="text-xs text-slate-400">Class</p><h2 className="font-black">II-A</h2></div></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Year" value="2nd"/><Metric label="Semester" value="III"/><Metric label="Students" value={students.length}/><Metric label="Average" value={`${pct}%`}/></div><button onClick={()=>setOpen(!open)} className="mt-5 flex w-full items-center justify-between rounded-xl bg-[#f7f6fd] p-3 text-sm font-bold text-[#37336e]">{open?'Hide class details':'Open detailed class attendance'}<ChevronRight className="h-4 w-4"/></button></div><div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-2 font-black"><AlertTriangle className="h-5 w-5 text-rose-500"/>Students at risk</div><p className="mt-2 text-3xl font-black">{rows.filter(r=>r.risk!=='Low').length}</p><p className="text-sm text-slate-500">Students below the required {required}% attendance.</p></div></div>
    {open&&<div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="grid gap-3 md:grid-cols-[1fr_220px_220px]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><Input className="pl-9" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search student..."/></div><select value={subject} onChange={e=>setSubject(e.target.value)} className="h-10 rounded-md border px-3 text-sm"><option value="all">All subjects</option>{Object.values(SUBJECTS).filter(s=>s.teacherName).map(s=><option key={s.code} value={s.code}>{s.name}</option>)}</select><div className="flex items-center gap-2"><CalendarDays className="h-4 w-4 text-[#5b51a3]"/><Input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="text-left text-xs text-slate-400"><th className="p-2">Student</th><th className="p-2">Roll No.</th><th className="p-2">Attendance %</th><th className="p-2">Present</th><th className="p-2">Absent</th><th className="p-2">Late</th><th className="p-2">Risk</th><th className="p-2">Selected Date</th></tr></thead><tbody>{rows.map(r=><tr className="border-t" key={r.s.id}><td className="p-2 font-semibold">{r.s.name}</td><td className="p-2">{String(r.s.email || '').match(/^(\d+)@/)?.[1] || r.s.id}</td><td className="p-2 font-black">{r.pc === null ? '—' : `${r.pc}%`}</td><td className="p-2 text-emerald-600">{r.p}</td><td className="p-2 text-rose-600">{r.ab}</td><td className="p-2 text-amber-600">{r.l}</td><td className="p-2"><Badge className={r.risk==='High'?'bg-rose-100 text-rose-700':r.risk==='Medium'?'bg-amber-100 text-amber-700':'bg-emerald-100 text-emerald-700'}>{r.risk}</Badge></td><td className="p-2">{r.day.length? r.day.map(x=>x.status).join(', '):'No record'}</td></tr>)}</tbody></table></div></div>}
    <div className="rounded-2xl border border-violet-100 bg-[#f5f2ff] p-5"><p className="font-black">Class analytics</p><p className="mt-1 text-sm text-slate-600">Use subject and date filters to compare student attendance, identify risk and review a specific day's records.</p></div>
  </DeanPage>
}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-xl bg-[#fafafe] p-3"><p className="text-xs text-slate-400">{label}</p><p className="mt-1 font-black">{value}</p></div>}
