'use client';

import { useMemo, useState } from 'react';
import { CalendarDays, ChevronRight, Search, Sparkles, X, Download } from 'lucide-react';
import { useDataContext } from '@/context/data-context';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { DeanPage } from '../dean-ui';
import { SUBJECTS } from '@/lib/timetable';

function rollNumber(student:any){ return String(student.email || '').match(/^(\d+)@/)?.[1] || String(student.id || ''); }
function downloadRiskExcel(rows:any[]){
  const headers=['Student','Student ID','Roll Number','Attendance %','Present','Absent','Late','Risk'];
  const html=`<table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr><td>${r.name}</td><td>${r.id}</td><td>${r.roll}</td><td>${r.pct}</td><td>${r.p}</td><td>${r.ab}</td><td>${r.late}</td><td>${r.risk}</td></tr>`).join('')}</tbody></table>`;
  const blob=new Blob([`<html><body>${html}</body></html>`],{type:'application/vnd.ms-excel'});
  const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download='attendavision-students-at-risk.xls'; a.click(); URL.revokeObjectURL(url);
}

const required = 75;
function stats(records:any[]){const p=records.filter(a=>a.status==='present').length;const ab=records.filter(a=>a.status==='absent').length;const late=records.filter(a=>a.status==='late').length;return {p,ab,late,total:records.length,pct:records.length?Math.round((p+late)/records.length*100):null}}

export default function StudentsPage(){
  const {students,attendance}=useDataContext();
  const [q,setQ]=useState(''); const [year,setYear]=useState('all'); const [section,setSection]=useState('all'); const [selected,setSelected]=useState<any>(null); const [date,setDate]=useState(new Date().toISOString().split('T')[0]);
  const list=students.filter(s=>`${s.name} ${s.id} ${s.email}`.toLowerCase().includes(q.toLowerCase()));
  const selectedStats=selected?stats(attendance.filter(a=>a.studentId===selected.id)):null;
  const subjectRows=selected?Object.values(SUBJECTS).filter(s=>s.teacherName).map(s=>{const records=attendance.filter(a=>a.studentId===selected.id && (a.classId===s.code || (a as any).subjectId===s.code || (a as any).subjectCode===s.code)); const st=stats(records); return {subject:s.name,teacher:s.teacherName,pct:st.pct,total:st.total};}).filter(r=>r.total>0):[];
  const riskRows=students.map(s=>{const st=stats(attendance.filter(a=>a.studentId===s.id)); return {...s,...st,roll:rollNumber(s),risk:st.pct===null?'No data':st.pct<65?'High':st.pct<required?'Medium':'Low'};}).filter(s=>s.pct!==null && s.pct<required);

  const dayRows=selected?attendance.filter(a=>a.studentId===selected.id&&a.date===date):[];

  return <DeanPage title="Students" subtitle="Search, filter and inspect every student in the department.">
    <div className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:flex-row"><div className="grid flex-1 gap-3 md:grid-cols-[1.4fr_180px_180px]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, roll number or student ID..." className="pl-9"/></div><select value={year} onChange={e=>setYear(e.target.value)} className="h-10 rounded-md border px-3 text-sm"><option value="all">All years</option><option>2nd Year</option></select><select value={section} onChange={e=>setSection(e.target.value)} className="h-10 rounded-md border px-3 text-sm"><option value="all">All sections</option><option>II-A</option></select></div><Button variant="outline" onClick={()=>downloadRiskExcel(riskRows)} disabled={!riskRows.length} className="shrink-0"><Download className="mr-2 h-4 w-4"/>Download At-Risk Excel</Button></div>
    <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[800px] text-sm"><thead><tr className="bg-[#fafafe] text-left text-xs text-slate-500"><th className="p-4">Student</th><th className="p-4">Roll No.</th><th className="p-4">Class / Section</th><th className="p-4">Attendance</th><th className="p-4">Risk</th><th className="p-4"/></tr></thead><tbody>{list.map((s,i)=>{const st=stats(attendance.filter(a=>a.studentId===s.id));const risk=st.pct===null?'No data':st.pct<65?'High':st.pct<required?'Medium':'Low';return <tr key={s.id} onClick={()=>setSelected(s)} className="cursor-pointer border-t text-left hover:bg-[#fafafe]"><td className="p-4 font-semibold">{s.name}<span className="block text-xs text-slate-400">Student ID {s.id}</span></td><td className="p-4">{rollNumber(s)}</td><td className="p-4">2nd Year · III · II-A</td><td className="p-4 font-black">{st.pct === null ? '—' : `${st.pct}%`}</td><td className="p-4"><Badge className={risk==='High'?'bg-rose-100 text-rose-700':risk==='Medium'?'bg-amber-100 text-amber-700':'bg-emerald-100 text-emerald-700'}>{risk}</Badge></td><td className="p-4"><ChevronRight className="h-4 w-4"/></td></tr>})}</tbody></table></div>

    {selected&&<div className="fixed inset-0 z-50 bg-black/30 p-4"><div className="ml-auto h-full max-w-3xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#6c67a2]">Dean student profile</p><h2 className="mt-1 text-2xl font-black">{selected.name}</h2><p className="text-sm text-slate-500">ID {selected.id} · 2nd Year · Semester III · Section II-A · Information Technology</p></div><Button variant="ghost" size="icon" onClick={()=>setSelected(null)}><X/></Button></div>
      <div className="mt-6 grid grid-cols-2 gap-3 md:grid-cols-4">{[['Overall',`${selectedStats?.pct}%`],['Present',selectedStats?.p||0],['Absent',selectedStats?.ab||0],['Late',selectedStats?.late||0]].map(([a,b])=><div className="rounded-xl bg-[#f7f7fc] p-4" key={String(a)}><p className="text-xs text-slate-400">{a}</p><b className="text-xl">{b}</b></div>)}</div>
      <div className="mt-5 rounded-2xl border p-5"><div className="flex items-center justify-between"><div><h3 className="font-black">Subject-wise attendance</h3><p className="text-xs text-slate-400">Current semester overview</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${selectedStats?.pct!<required?'bg-rose-50 text-rose-700':'bg-emerald-50 text-emerald-700'}`}>{selectedStats?.pct!<required?'At Risk':'On Track'}</span></div><div className="mt-4 space-y-3">{subjectRows.map(r=><div key={r.subject}><div className="flex justify-between text-sm"><span className="font-semibold">{r.subject}</span><span className="font-bold">{r.pct}%</span></div><div className="mt-1 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-[#5ba7be]" style={{width:`${r.pct}%`}}/></div><p className="mt-1 text-[11px] text-slate-400">Teacher: {r.teacher}</p></div>)}</div></div>
      <div className="mt-5 rounded-2xl border p-5"><div className="flex items-center gap-2"><CalendarDays className="h-5 w-5 text-[#5b51a3]"/><h3 className="font-black">Daily attendance calendar</h3></div><div className="mt-3 flex flex-col gap-3 sm:flex-row sm:items-center"><Input type="date" value={date} onChange={e=>setDate(e.target.value)} className="sm:w-52"/><span className="text-sm text-slate-500">Selected date: {date}</span></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[600px] text-sm"><thead><tr className="text-left text-xs text-slate-400"><th className="p-2">Time</th><th className="p-2">Subject</th><th className="p-2">Teacher</th><th className="p-2">Room</th><th className="p-2">Status</th></tr></thead><tbody>{dayRows.map((r:any)=><tr className="border-t" key={r.id}><td className="p-2">{r.time||'—'}</td><td className="p-2">{r.subject||r.className||r.classId||'—'}</td><td className="p-2">{r.teacher||r.teacherName||r.teacherEmail||'—'}</td><td className="p-2">{r.room||'—'}</td><td className="p-2"><Badge variant="outline">{r.status}</Badge></td></tr>)}</tbody></table>{!dayRows.length&&<div className="mt-3 rounded-xl border border-dashed p-5 text-center text-xs text-slate-400">No attendance was recorded for this student on this date.</div>}</div></div>
      <div className="mt-5 grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-violet-100 bg-[#f5f2ff] p-5"><div className="flex items-center gap-2 font-black"><Sparkles className="h-5 w-5"/>AI risk analysis</div><p className="mt-2 text-sm text-slate-600">Risk level: {selectedStats?.pct!<65?'High':selectedStats?.pct!<required?'Medium':'Low'}. AI observations are advisory and do not replace the Dean's academic decision.</p><p className="mt-2 text-xs text-slate-500">Suggested review: compare recent attendance trend with class requirements.</p></div><div className="rounded-2xl border p-5"><h3 className="font-black">Attendance history</h3><div className="mt-3 space-y-2">{attendance.filter(a=>a.studentId===selected.id).slice(0,8).map(a=><div key={a.id} className="flex justify-between border-b py-2 text-sm"><span>{a.date}</span><Badge variant="outline">{a.status}</Badge></div>)}</div></div></div>
    </div></div>}
  </DeanPage>
}
